services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: medsmart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/medsmart
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-here}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600s}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY:-sk-your-deepseek-api-key-here}
      DEEPSEEK_BASE_URL: ${DEEPSEEK_BASE_URL:-https://api.deepseek.com}
      DEEPSEEK_MODEL: ${DEEPSEEK_MODEL:-deepseek-chat}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      UPLOAD_DIR: ${UPLOAD_DIR:-./uploads}
      PORT: 3000
    ports:
      - '3000:3000'

volumes:
  pgdata:
  localstack_data:
